# Generated by Django 3.2.25 on 2024-04-13 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code_airline', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FlyReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fists_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('second_last_name', models.CharField(max_length=30)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('fly_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fly')),
            ],
        ),
        migrations.CreateModel(
            name='OrderReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_order', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TickeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pay', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=10)),
                ('fly_reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.flyreservation')),
            ],
        ),
        migrations.AddField(
            model_name='flyreservation',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.orderreservation'),
        ),
        migrations.AddField(
            model_name='flyreservation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
